/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconLucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    IconLucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    IconLucideCheck: typeof import('~icons/lucide/check')['default']
    IconLucideCoffee: typeof import('~icons/lucide/coffee')['default']
    IconLucideCopy: typeof import('~icons/lucide/copy')['default']
    IconLucideExternalLink: typeof import('~icons/lucide/external-link')['default']
    IconLucideMail: typeof import('~icons/lucide/mail')['default']
    IconSimpleIconsCachyos: typeof import('~icons/simple-icons/cachyos')['default']
    IconSimpleIconsCloudflare: typeof import('~icons/simple-icons/cloudflare')['default']
    IconSimpleIconsDiscord: typeof import('~icons/simple-icons/discord')['default']
    IconSimpleIconsDocker: typeof import('~icons/simple-icons/docker')['default']
    IconSimpleIconsExpress: typeof import('~icons/simple-icons/express')['default']
    IconSimpleIconsGeode: typeof import('~icons/simple-icons/geode')['default']
    IconSimpleIconsGithub: typeof import('~icons/simple-icons/github')['default']
    IconSimpleIconsGnubash: typeof import('~icons/simple-icons/gnubash')['default']
    IconSimpleIconsJavascript: typeof import('~icons/simple-icons/javascript')['default']
    IconSimpleIconsJetbrains: typeof import('~icons/simple-icons/jetbrains')['default']
    IconSimpleIconsLuau: typeof import('~icons/simple-icons/luau')['default']
    IconSimpleIconsNextdotjs: typeof import('~icons/simple-icons/nextdotjs')['default']
    IconSimpleIconsNodedotjs: typeof import('~icons/simple-icons/nodedotjs')['default']
    IconSimpleIconsPython: typeof import('~icons/simple-icons/python')['default']
    IconSimpleIconsRadixui: typeof import('~icons/simple-icons/radixui')['default']
    IconSimpleIconsReact: typeof import('~icons/simple-icons/react')['default']
    IconSimpleIconsRedis: typeof import('~icons/simple-icons/redis')['default']
    IconSimpleIconsSqlite: typeof import('~icons/simple-icons/sqlite')['default']
    IconSimpleIconsTwitter: typeof import('~icons/simple-icons/twitter')['default']
    IconSimpleIconsTypescript: typeof import('~icons/simple-icons/typescript')['default']
    IconSimpleIconsVite: typeof import('~icons/simple-icons/vite')['default']
    IconSimpleIconsVscodium: typeof import('~icons/simple-icons/vscodium')['default']
    IconSimpleIconsVuedotjs: typeof import('~icons/simple-icons/vuedotjs')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    ParticleBackground: typeof import('./components/ParticleBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
